### ISSUE TITLE
Bug Report - Document Scraper Path Issue on Windows Machine

### ISSUE THREAD

**Issue by dn1** [scales-okn/PACER-tools#4]
Hello - I'm on a Windows machine and attempting to run the document scraper as part of the getting started tutorial in the main repo `readme.md`. I've successfully run the query scraper and the docket scraper, but am running into an issue with the document scraper. See the traceback in the screenshot below. I've tried my hand at debugging this, but the solution escapes me - as far as I can tell the variable for the filepath to the location of the downloaded HTML docket files is empty, but that's about as far as I've gotten. Thanks very much for your help - PACER-tools has been enormously useful so far in making queries and collecting dockets significantly easier.
![image](https://user-images.githubusercontent.com/30941349/149590230-96389667-4ae3-4b07-a07f-ad1b57c91b0a.png)

**Comment by mangangreg** [comment]
Hi there, glad to hear PACER-tools has been useful for you so far! The issue seems to be that you have not supplied a `--document-input`. The latest commit https://github.com/scales-okn/PACER-tools/commit/95ff78cfe657d4a25cb6e806adf57d9fae27ecb3 has added an explicit catch for this, as well as updating the scraper and adding more detail to the [scraper readme](https://github.com/scales-okn/PACER-tools/tree/master/code/downloader#5-download-specific-documents) . If you take a look at the section on [downloading specific documents](https://github.com/scales-okn/PACER-tools/tree/master/code/downloader#5-download-specific-documents) this should be of help to you. Thanks!

**Comment by dn1** [comment]
Hi - just a question about this issue. The main [readme](https://github.com/scales-okn/PACER-tools/blob/master/README.md#5-document-scraper) mentions that running without `--document-input` means the document downloader will default to all dockets in the /html directory. This is where I'm running into the error. Is this functionality not currently supported? Should I just use a csv `--document-input` in all situations? Thanks again!
